import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {type: 'doc', id: 'intro', label: 'Introduction'},
    {
      type: 'category',
      label: 'Guide',
      items: [
        {
          type: 'category',
          label: 'Getting Started',
          items: [{type: 'autogenerated', dirName: 'getting-started'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [{type: 'autogenerated', dirName: 'tutorials'}],
    },
    {
      type: 'category',
      label: 'Language Reference',
      items: [
        {
          type: 'category',
          label: 'Modifiers',
          items: [{type: 'autogenerated', dirName: 'language-reference/modifiers'}],
        },
        {
          type: 'category',
          label: 'Vectors',
          items: [{type: 'autogenerated', dirName: 'language-reference/vectors'}],
        },
      ],
    },
  ],
};

export default sidebars;
